[project]
name = "sbg-ins-monitoring"
version = "0.1.0"
description = "SBG Systems - INS Monitoring system"
authors = [
    { name = "SBG Systems" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "flask (<4.0.0)",
    "requests (<3.0.0)",
    "numpy (<3.0.0)",
    "pysbgecom (>=6.0,<6.1.0)",
    "gpiozero (>=2.0) ; platform_machine == 'aarch64' or platform_machine == 'armv7l'",
    "lgpio ; platform_machine == 'aarch64' or platform_machine == 'armv7l'" 
]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
pysbgecom = {path = "vendor/pysbgecom-6.0-py3-none-any.whl"}

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
